#Error Handling

try:
    print(x)
except NameError:
    print("User hasn't been defined yet.")